# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

services:
  vllm-service:
    image: opea/vllm-gaudi:latest
    container_name: vllm-gaudi-server
    ports:
      - "8008:80"
    volumes:
      - "./data/:/data"
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      HF_TOKEN: ${HUGGINGFACEHUB_API_TOKEN}
      HABANA_VISIBLE_DEVICES: all
      OMPI_MCA_btl_vader_single_copy_mechanism: none
      LLM_MODEL_ID: ${LLM_MODEL_ID}
    runtime: habana
    cap_add:
      - SYS_NICE
    ipc: host
    command: --enforce-eager --model $LLM_MODEL_ID --tensor-parallel-size 1 --host 0.0.0.0 --port 80 --block-size 128 --max-num-seqs 256 --max-seq_len-to-capture 2048
  llm-docsum-vllm:
    image: ${REGISTRY:-opea}/llm-docsum-vllm::${TAG:-latest}
    container_name: llm-docsum-vllm-gaudi-server
    ports:
      - "9000:9000"
    ipc: host
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      vLLM_ENDPOINT: ${LLM_ENDPOINT}
      HUGGINGFACEHUB_API_TOKEN: ${HUGGINGFACEHUB_API_TOKEN}
      LLM_MODEL_ID: ${LLM_MODEL_ID}
    restart: unless-stopped
  whisper:
    image: ${REGISTRY:-opea}/whisper:${TAG:-latest}
    container_name: whisper-service
    ports:
      - "7066:7066"
    ipc: host
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      HABANA_VISIBLE_DEVICES: all
      OMPI_MCA_btl_vader_single_copy_mechanism: none
    runtime: habana
    cap_add:
      - SYS_NICE
    restart: unless-stopped

  dataprep-audio2text:
    image: ${REGISTRY:-opea}/dataprep-audio2text:${TAG:-latest}
    container_name: dataprep-audio2text-service
    ports:
      - "9199:9099"
    ipc: host
    environment:
      A2T_ENDPOINT: ${A2T_ENDPOINT}

  dataprep-video2audio:
    image: ${REGISTRY:-opea}/dataprep-video2audio:${TAG:-latest}
    container_name: dataprep-video2audio-service
    ports:
      - "7078:7078"
    ipc: host
    environment:
      V2A_ENDPOINT: ${V2A_ENDPOINT}

  dataprep-multimedia2text:
    image: ${REGISTRY:-opea}/dataprep-multimedia2text:${TAG:-latest}
    container_name: dataprep-multimedia2text
    ports:
      - "7079:7079"
    ipc: host
    environment:
      V2A_ENDPOINT: ${V2A_ENDPOINT}
      A2T_ENDPOINT: ${A2T_ENDPOINT}

  docsum-gaudi-backend-server:
    image: ${REGISTRY:-opea}/docsum:${TAG:-latest}
    container_name: docsum-gaudi-backend-server
    depends_on:
      - vllm-service
      - llm-docsum-vllm
      - dataprep-multimedia2text
      - dataprep-video2audio
      - dataprep-audio2text
    ports:
      - "8888:8888"
    environment:
      - no_proxy=${no_proxy}
      - https_proxy=${https_proxy}
      - http_proxy=${http_proxy}
      - MEGA_SERVICE_HOST_IP=${MEGA_SERVICE_HOST_IP}
      - DATA_SERVICE_HOST_IP=${DATA_SERVICE_HOST_IP}
      - LLM_SERVICE_HOST_IP=${LLM_SERVICE_HOST_IP}

    ipc: host
    restart: always

  docsum-ui:
    image: ${REGISTRY:-opea}/docsum-ui:${TAG:-latest}
    container_name: docsum-gaudi-ui-server
    depends_on:
      - docsum-gaudi-backend-server
    ports:
      - "5173:5173"
    environment:
      - no_proxy=${no_proxy}
      - https_proxy=${https_proxy}
      - http_proxy=${http_proxy}
      - BACKEND_SERVICE_ENDPOINT=${BACKEND_SERVICE_ENDPOINT}
      - DOC_BASE_URL=${BACKEND_SERVICE_ENDPOINT}
    ipc: host
    restart: always

networks:
  default:
    driver: bridge
